### ISSUE TITLE
KeyError: 'details' when using US zip codes

### ISSUE THREAD

**Issue by sqr** [vrslev/ikea-api-client#33]
Hello, I am investigating the following error:

```shell
Traceback (most recent call last):
  File "ikea.py", line 17, in <module>
    api.OrderCapture(zip_code="02215")
  File "/home/square/ikea-api/ikea_api/core.py", line 64, in OrderCapture
    return OrderCapture(self._token, zip_code)()
  File "/home/square/ikea-api/ikea_api/endpoints/order_capture/__init__.py", line 29, in __call__
    return self.get_delivery_services()
  File "/home/square/ikea-api/ikea_api/endpoints/order_capture/__init__.py", line 93, in get_delivery_services
    delivery_area = self._get_delivery_area(checkout)
  File "/home/square/ikea-api/ikea_api/endpoints/order_capture/__init__.py", line 80, in _get_delivery_area
    response = self._call_api(
  File "/home/square/ikea-api/ikea_api/api.py", line 70, in _call_api
    self._error_handler(response.status_code, response_dict)
  File "/home/square/ikea-api/ikea_api/endpoints/order_capture/__init__.py", line 33, in _error_handler
    raise OrderCaptureError(response)
  File "/home/square/ikea-api/ikea_api/errors.py", line 44, in __init__
    if response["message"] == response["details"]
KeyError: 'details'
```

It seems to happen with all the United States zip codes I have tried. 

My script is as follows:

```python
from ikea_api import IkeaApi

api = IkeaApi(
    token=...,  # If you already have a token and stored it somewhere
    country_code="us",
    language_code="en",
)

api.login_as_guest()

cart = api.Cart
cart.add_items({"90446761": 1})
# print(cart.show())

api.OrderCapture(zip_code="02215")
```

Showing the cart works.

I am going to query the api manually and see how the response looks, in case I can spot the problem.

**Comment by sqr** [comment]
Fixed this, will send a PR in a little bit
