### ISSUE TITLE
Only able to get_items from Russia

### ISSUE THREAD

**Issue by marosige** [vrslev/ikea-api-client#87]
If I change the COUNTRY_CODE and LANGUAGE_CODE from "ru" to "hu" or "at" it's not working anymore. With default values it works fine and I get a response.

If source is:
```
from ikea_api.wrappers import get_items
from ikea_api._constants import Constants

Constants.COUNTRY_CODE = "ru"
Constants.LANGUAGE_CODE = "ru"

print(get_items(["09251777"]))
```

Response is:
```
[ParsedItem(is_combination=True, item_code='49251780', name='КЛИППАН, 2-местный диван, Кабуса темно-серый', image_url='https://www.ikea.com/ru/ru/images/products/klippan-2-mestnyy-divan-kabusa-temno-seryy__0562986_pe663639_s5.jpg', weight=0.0, child_items=[ChildItem(name=None, item_code='50501293', weight=0.0, qty=1), ChildItem(name=None, item_code='00398726', weight=0.0, qty=1)], price=14999, url=HttpUrl('https://www.ikea.com/ru/ru/p/klippan-klippan-2-mestnyy-divan-kabusa-temno-seryy-s49251780/', scheme='https', host='www.ikea.com', tld='com', host_type='domain', port='443', path='/ru/ru/p/klippan-klippan-2-mestnyy-divan-kabusa-temno-seryy-s49251780/'), category_name='Двухместные диваны', category_url=HttpUrl('https://www.ikea.com/ru/ru/cat/dvuhmestnye-divany-10668/', scheme='https', host='www.ikea.com', tld='com', host_type='domain', port='443', path='/ru/ru/cat/dvuhmestnye-divany-10668/'))]
```

If source is:
```
from ikea_api.wrappers import get_items
from ikea_api._constants import Constants

Constants.COUNTRY_CODE = "hu"
Constants.LANGUAGE_CODE = "hu"

print(get_items(["09251777"]))
```

Response is:
```
Traceback (most recent call last):
  File "/Users/gergelymarosi/_hobbi/ikea/main.py", line 7, in <module>
    print(get_items(["09251777"]))
  File "/Users/gergelymarosi/_hobbi/ikea/venv/lib/python3.9/site-packages/ikea_api/wrappers/__init__.py", line 192, in get_items
    fetched_items_ingka_pip = _get_ingka_pip_items(pending_item_codes)
  File "/Users/gergelymarosi/_hobbi/ikea/venv/lib/python3.9/site-packages/ikea_api/wrappers/__init__.py", line 164, in _get_ingka_pip_items
    ingka_items = _get_ingka_items(item_codes)
  File "/Users/gergelymarosi/_hobbi/ikea/venv/lib/python3.9/site-packages/ikea_api/wrappers/__init__.py", line 142, in _get_ingka_items
    responses.append(fetcher(item_codes_chunk))
  File "/Users/gergelymarosi/_hobbi/ikea/venv/lib/python3.9/site-packages/ikea_api/_endpoints/item_ingka.py", line 39, in __call__
    return self._get(params={"itemNos": item_codes})
  File "/Users/gergelymarosi/_hobbi/ikea/venv/lib/python3.9/site-packages/ikea_api/_api.py", line 60, in _get
    return self._handle_response(response)
  File "/Users/gergelymarosi/_hobbi/ikea/venv/lib/python3.9/site-packages/ikea_api/_api.py", line 44, in _handle_response
    self._error_handler(response)
  File "/Users/gergelymarosi/_hobbi/ikea/venv/lib/python3.9/site-packages/ikea_api/_endpoints/item_ingka.py", line 34, in _error_handler
    raise ItemFetchError(response, item_codes)
ikea_api.exceptions.ItemFetchError: (400, '{"error":{"code":400,"message":"invalid GetItemCommunicationsRequest.ClassUnitType: value is not a valid enum"}}')
```

**Comment by vrslev** [comment]
Hey there! Thanks for leaving the issue!

I guess it is relevant to #83: Ingka endpoint works only with `Constants.COUNTRY_CODE = "ru"`. Also Pip endpoint is not available in your region, that's why `get_items` wouldn't work event if you set country to `"ru"`. I suggest to use private [`_get_ingka_items`](https://github.com/vrslev/ikea-api-client/blob/7324d39ae3b481eb2006281c31bc17c2ec524f17/src/ikea_api/wrappers/__init__.py#L138-L146) endpoint that returns [`IngkaItem`](https://github.com/vrslev/ikea-api-client/blob/7324d39ae3b481eb2006281c31bc17c2ec524f17/src/ikea_api/wrappers/types.py#L54-L60). You also can try [`_get_iows_items`](https://github.com/vrslev/ikea-api-client/blob/7324d39ae3b481eb2006281c31bc17c2ec524f17/src/ikea_api/wrappers/__init__.py#L126-L135), but it is deprecated. Here's working example of `_get_ingka_items` usage:

```python
from ikea_api._constants import Constants
from ikea_api.wrappers import _get_ingka_items as get_ingka_items
from ikea_api.wrappers.types import IngkaItem

Constants.COUNTRY_CODE = "ru"
Constants.LANGUAGE_CODE = "hu"

item_codes = ["09251777"]
items: list[IngkaItem] = get_ingka_items(item_codes)
print(items)
```
It outputs:
```python
[
    IngkaItem(
        is_combination=True,
        item_code="09251777",
        name="KLIPPAN, 2sz. kanapé, Kabusa sszürke",
        image_url="https://www.ikea.com/hu/hu/images/products/klippan-2sz-kanape-kabusa-sszuerke__0562986_pe663639_s5.jpg",
        weight=0.0,
        child_items=[
            ChildItem(name=None, item_code="10072256", weight=0.0, qty=1),
            ChildItem(name=None, item_code="90398722", weight=0.0, qty=1),
        ],
    )
]
```

**Comment by vrslev** [comment]
Closing the issue. If my solution doesn't work for you let me know!
